services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
<<<<<<< HEAD
    - postgres
=======
      - postgres
>>>>>>> 6aee0ae4244b4d10bc3e457761fdf372cf9dbc7d
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
<<<<<<< HEAD
    - 5672:5672
    - 15672:15672
    networks:
    - postgres
=======
      - 5672:5672
      - 15672:15672
    networks:
      - postgres
>>>>>>> 6aee0ae4244b4d10bc3e457761fdf372cf9dbc7d

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
